param(
    [string]$WslPath = "/home/liusz10/wiki/WeKnora-fork",
    [string]$Remote = "origin"
)

$ErrorActionPreference = "Stop"

$repoRoot = (& git rev-parse --show-toplevel).Trim()
if (-not $repoRoot) {
    throw "Run this script inside a Git repository."
}

$hookPath = Join-Path $repoRoot ".git/hooks/pre-push"
$logPath = (Join-Path $repoRoot ".git/wsl-sync.log") -replace "\\", "/"
$scriptPath = Join-Path $repoRoot "scripts/sync-wsl-deploy.ps1"
$scriptPathForHook = $scriptPath -replace "\\", "/"

$hook = @"
#!/bin/sh
# Auto-generated by scripts/install-wsl-sync-hook.ps1.
# Git has no post-push hook, so this pre-push hook starts a detached sync job.
# The job waits until the remote branch reaches the pushed SHA before pulling in WSL.

while read local_ref local_sha remote_ref remote_sha
do
  case "`$local_ref" in
    refs/heads/*)
      branch="`${local_ref#refs/heads/}"
      MSYS2_ARG_CONV_EXCL='*' powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "$scriptPathForHook" -WslPath "$WslPath" -Remote "$Remote" -Branch "`$branch" -ExpectedSha "`$local_sha" >> "$logPath" 2>&1 &
      ;;
  esac
done

exit 0
"@

Set-Content -LiteralPath $hookPath -Value $hook -NoNewline -Encoding ASCII

$gitExe = (Get-Command git.exe -ErrorAction SilentlyContinue).Source
if ($gitExe) {
    $gitRoot = Split-Path (Split-Path $gitExe -Parent) -Parent
    $chmod = Join-Path $gitRoot "usr\bin\chmod.exe"
    if (Test-Path -LiteralPath $chmod) {
        & $chmod +x $hookPath
    }
}

Write-Host "Installed pre-push hook at $hookPath"
Write-Host "WSL deploy path: $WslPath"
Write-Host "Remote: $Remote"
Write-Host "Log: $logPath"
